Update index.html
htmlacademy-htmlcss/1531933-sedona-29 pull request #2
Opened 2020-09-11 12:58 UTC by cntetix

сделала разметку главное страницы

2020-09-11 14:10 UTC, Vallek requested changes
Привет! Поздравляю с началом первой полноценной практики:) В целом хорошо. Здорово, что уже семантические есть обертки (header и прочее). Если какие-то вопросы по комментам и вообще, пиши разберем на созвоне.

2020-09-11 14:10 UTC, Vallek commented on index.html
> +          <a href="#">ТЕЛ: +7(495) 666-01-66</a>
Для телефона есть специальный формат записи путей. Может вам еще будут про это рассказывать. Но можно тут почитать: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/a#Linking_to_telephone_numbers

2020-09-11 14:10 UTC, Vallek commented on index.html
> +          <i>Gorgeous</i>
Не уверен, почему ты выбрала <i>. Но учти, что внешний вид (курсив) к выбору элемента не имеет отношения. Это все будет через css делаться.

2020-09-13 09:42 UTC, Vallek requested changes
Привет! Почти все исправлено. Но еще прау замечаний по заголовкам.

2020-09-13 09:42 UTC, Vallek commented on index.html
>          <h4>Седона - небольшой городок в Аризоне, заслуживающий большего!</h4>
Тут скорее заголовок второго уровня. Он ведь размечает часть страницы. Как и "Заинтересовались?".
У нас нет h1, но пропускать дальше уровни особо причин нет.

2020-09-13 09:42 UTC, Vallek commented on index.html
>            <h4>Настоящий городок</h4>
Соответственно это будет h3.

2020-09-13 09:42 UTC, Vallek commented on index.html
> +        <ol>
Я бы сделал это неупорядоченным. Хоть там и есть номера, но по смыслу порядок не важен. И тебе придется убирать те числа, которые автоматом там появляются. Те номера которые с символом № делаются не вручную. Но про это позже может расскажут или я покажу потом.

2020-09-14 08:13 UTC, cntetix reviewed
поменяла заголовки

2020-09-14 08:29 UTC, merged