css file creation
htmlacademy-htmlcss/1531933-sedona-29 pull request #3
Opened 2020-09-15 15:18 UTC by cntetix

2020-09-15 16:15 UTC, Vallek requested changes
Привет! В целом хорошо, многое уже сделала. Смотрю переменные осилила сразу:)

1. Советую разобраться с оформлением кода в плане отступов как можно раньше. Это мешает его читать. А потом будет сложнее. В редакторах есть авто исправление по команде reindent lines или похожее. Можно выделять часть сначала.
2. Вижу, что ты указала шрифт только для body. Лучше указывать для каждого элемента, где это нужно. Он ведь может поменяться.
3. Еще не хватает стилизации состояний (по наведению). Сейчас нужно сделать только текст и фоны.

2020-09-16 09:03 UTC, cntetix commented
css edit

2020-09-16 11:13 UTC, Vallek requested changes
Привет! Пара моментов еще.

Я только сейчас заметил, чт оу тебя в папке css весь репозиторий normalize. Так не надо делать:) Достаточно только файла css.

2020-09-16 11:13 UTC, Vallek commented on css/style.css
> +          body{
Я наверно не очень удачно выразился про шрифт в body. Его можно и нужно указывать. Просто вместе с основным стоит это делать для других элементов.

2020-09-17 09:30 UTC, merged